import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar/Navbar";
import { navbarData } from "@/data/navbarData";

export const metadata: Metadata = {
  title: "Flight Routes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar items={navbarData} />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
